name: Deploy Picoratch

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16 # Scratchはこのバージョンが一番安定します

      - name: Install dependencies
        # --legacy-peer-deps をつけることで、古い部品同士の衝突エラーを防ぎます
        run: npm install --legacy-peer-deps

      - name: Build Picoratch
        # メモリ不足で落ちないように 4GB まで使えるように設定します
        run: NODE_OPTIONS=--max_old_space_size=4096 npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
