name: Deploy Picoratch

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # 16と20の間（18）にします！

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Picoratch
        run: |
          export CI=false
          # --openssl-legacy-provider を追加して、古いルールでの組み立てを許可します
          export NODE_OPTIONS="--max_old_space_size=4096 --openssl-legacy-provider"
          npm run build
        env:
          NODE_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/scratch-gui/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
